name: 'Auto Code Reviewer'
description: 'Use LLMs to perform automatic code reviews'
author: 'admin-rimba'
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
inputs:
  github_token:
    description: 'github token'
    required: true
  openai_api_key:
    description: 'OpenAI API key'
    required: true
  model_name: 
    description: 'OpenAI model name'
    default: 'o1-preview'
  model_temperature:
    description: 'OpenAI model temperature'
    default: '0'
  exclude_files:
    description: "Provide a wildcard expression to exclude files from code review. For example, `*.md` will exclude all markdown files. Multiple expressions are supported via commas, eg `*.js, *.cjs`"
    required: false
    default: ""

runs:
  using: 'node20'
  main: 'dist/index.js'
